using System;
using System.Collections.Generic;

namespace Tasalia.Intranet.DataBase.Models
{
    public partial class Raw
    {
        public int RawId { get; set; }
        public Guid ProcessGuid { get; set; }
        public bool Processed { get; set; }
        public DateTime? ProcessedTime { get; set; }
        public string X { get; set; }
        public string Agno { get; set; }
        public string Numero { get; set; }
        public string Suplemento { get; set; }
        public string Version { get; set; }
        public string Delegacio { get; set; }
        public string MonedaId { get; set; }
        public string NroCliente { get; set; }
        public string Siglas { get; set; }
        public string CodigoTasador { get; set; }
        public string FechaTas { get; set; }
        public string Codentidad { get; set; }
        public string Entidad { get; set; }
        public string Solicitante { get; set; }
        public string NucleoPos { get; set; }
        public string Sucursal { get; set; }
        public string NumeroRegistro { get; set; }
        public string Codencargo { get; set; }
        public string Empresa { get; set; }
        public string Nif { get; set; }
        public string FechaVis { get; set; }
        public string Finalidad { get; set; }
        public string Registro { get; set; }
        public string Paisid { get; set; }
        public string Codmunicipio { get; set; }
        public string Tipoficha { get; set; }
        public string Supadotas { get; set; }
        public string Totasuelo { get; set; }
        public string Cterneto { get; set; }
        public string PorcReper { get; set; }
        public string ProvinciaCodigo { get; set; }
        public string Provincia { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string NumeroVia { get; set; }
        public string Planta { get; set; }
        public string Puerta { get; set; }
        public string Piso { get; set; }
        public string Dato1 { get; set; }
        public string Dato1id { get; set; }
        public string Dato2 { get; set; }
        public string Dato2id { get; set; }
        public string Dato3 { get; set; }
        public string Dato3id { get; set; }
        public string Dato4 { get; set; }
        public string Dato4id { get; set; }
        public string Tipocalle { get; set; }
        public string Piso1 { get; set; }
        public string Puerta1 { get; set; }
        public string Via { get; set; }
        public string Tipo { get; set; }
        public string TipoVia { get; set; }
        public string Duplex { get; set; }
        public string Atico { get; set; }
        public string Codpos { get; set; }
        public string Distrito { get; set; }
        public string Zona { get; set; }
        public string RefCatast { get; set; }
        public string Finca { get; set; }
        public string Uso { get; set; }
        public string TipoInmueble { get; set; }
        public string ValsegTotal { get; set; }
        public string Libro { get; set; }
        public string Tomo { get; set; }
        public string Folio { get; set; }
        public string Distribucion { get; set; }
        public string Estadouso { get; set; }
        public string ValorMercado { get; set; }
        public string ValsegUnid { get; set; }
        public string SuperficieParcela { get; set; }
        public string SuperficieUtil { get; set; }
        public string SuperficieConstruidaPpzc { get; set; }
        public string SuperficieConstruidaPrivativa { get; set; }
        public string AlturaLib { get; set; }
        public string FachadaPr { get; set; }
        public string FachadaSe { get; set; }
        public string Fondo { get; set; }
        public string LuzLibre { get; set; }
        public string Antiguedad { get; set; }
        public string AgnoReform { get; set; }
        public string AgnoReforma { get; set; }
        public string CosteReposiciónActual { get; set; }
        public string CosteReposiciónFinal { get; set; }
        public string IndicedepreciacionEstadoCon { get; set; }
        public string ValorUniCosteCons { get; set; }
        public string PDepreAplicada { get; set; }
        public string ValorUniSueloReper { get; set; }
        public string Gastosnece { get; set; }
        public string Inddepreci { get; set; }
        public string NombUnidad { get; set; }
        public string CalefaccA { get; set; }
        public string Bagnos { get; set; }
        public string Dormitorio { get; set; }
        public string CalidadConstruccion { get; set; }
        public string CalidadUbicacion { get; set; }
        public string Vistas { get; set; }
        public string PavimenDormitorios { get; set; }
        public string PavimenComedorEstar { get; set; }
        public string PavimenSalon { get; set; }
        public string PavimenCocina { get; set; }
        public string PavimenBagno { get; set; }
        public string Condicionantes { get; set; }
        public string Advertencias { get; set; }
        public string Carpintext { get; set; }
        public string Carpintint { get; set; }
        public string Catastronavarra { get; set; }
        public string ReformasC { get; set; }
        public string Estadoactu { get; set; }
        public string Paredes { get; set; }
        public string Techos { get; set; }
        public string Garaje { get; set; }
        public string Suelos { get; set; }
        public string Situacion { get; set; }
        public string Provincia1 { get; set; }
        public string Habitantes { get; set; }
        public string Titular { get; set; }
        public string Cargas { get; set; }
        public string ImporteCargas { get; set; }
        public string Sto { get; set; }
        public string Altura { get; set; }
        public string Alturaplanta { get; set; }
        public string Acogidonor { get; set; }
        public string Ascensor { get; set; }
        public string Ascensores { get; set; }
        public string Vpo { get; set; }
        public string VVpo { get; set; }
        public string Rentasnetas { get; set; }
        public string VanRentasnetas { get; set; }
        public string Rentasactuales { get; set; }
        public string VanRentasactuales { get; set; }
        public string Rentasesperadas { get; set; }
        public string VanRentasesperadas { get; set; }
        public string Residen { get; set; }
        public string VAgrupaci { get; set; }
        public string VTasacion { get; set; }
        public string VSeguro { get; set; }
        public string EstimacionTecnica { get; set; }
        public string Piscina { get; set; }
        public string InstalacionesDeportivas { get; set; }
        public string Jardin { get; set; }
        public string Reformas { get; set; }
        public string VCalid { get; set; }
        public string VUbica { get; set; }
        public string VLumin { get; set; }
        public string VAlturaplan { get; set; }
        public string K { get; set; }
        public string ReferenciaCatastral { get; set; }
        public string RefCatastT { get; set; }
        public string Vinculada { get; set; }
        public string Ginstalaid { get; set; }
        public string Gdistriid { get; set; }
        public string Unidadid { get; set; }
        public string Gobraid { get; set; }
        public string Gdoclegid { get; set; }
        public string Tipomodulo { get; set; }
        public string ValuniComp { get; set; }
        public string Mettasa { get; set; }
        public string Rreal { get; set; }
        public string ValuniActRco { get; set; }
        public string ValuniActRma { get; set; }
        public string ValuniActRee { get; set; }
        public string Valunisueterreno { get; set; }
        public string Edificabterreno { get; set; }
        public string Supparcterrfir { get; set; }
        public string UsoCultivo { get; set; }
        public string ClaseTerreno { get; set; }
        public string Rentamesco { get; set; }
        public string Coscondepr { get; set; }
        public string Repersuelo { get; set; }
        public string DatosSareb { get; set; }
        public string Ocupado { get; set; }
        public string VisitadoC { get; set; }
        public string Visitado { get; set; }
        public string Porinmpro { get; set; }
        public string Documentacion { get; set; }
        public string Imagypdf { get; set; }
        public string Comprobacion { get; set; }
        public string TipoocupanC { get; set; }
        public string Tipoocupan { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Altitud { get; set; }
        public string Delegacion { get; set; }
        public string Moneda { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
